export async function onRequestGet(context) {
  try {
    const { env, params } = context;
    const slug = params.slug || new URL(context.request.url).pathname.replace('/blog/', '').replace(/\/$/, '');
    const a = await env.DB.prepare('SELECT * FROM articles WHERE slug=? AND is_published=1').bind(slug).first();
    if (!a) return new Response('Not found', { status: 404 });
    const l = await env.DB.prepare('SELECT COUNT(*) as c FROM likes WHERE article_id=?').bind(a.id).first();
    return new Response(render(a, l.c), {
      headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'public, max-age=600, s-maxage=3600' }
    });
  } catch (e) { return new Response('Error', { status: 500 }); }
}

function render(a, likes) {
  var time = (a.created_at || '').replace('T', ' ').slice(0, 16);
  var tags = '', ts = (a.tags || '').split(',').filter(Boolean);
  for (var i = 0; i < ts.length; i++) tags += '<span class="blog-tag">#' + esc(ts[i].trim()) + '</span>';

  var md = JSON.stringify(a.content_md || '');

  var h = '<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>' + esc(a.title) + '</title><link rel="stylesheet" href="/style.css">';
  h += '<script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"><\/script>';
  h += '</head><body>';
  h += '<nav class="navbar"><div class="nav-inner"><a href="/" class="nav-brand">' + esc(a.title) + '</a><div class="nav-spacer"></div><a href="/blog" class="nav-link">← 笔记</a></div></nav>';
  h += '<div class="article-wrapper"><article>';
  if (a.cover_image) h += '<img src="' + esc(a.cover_image) + '" class="article-cover" alt="">';
  h += '<header class="article-header"><h1 class="article-title">' + esc(a.title) + '</h1>';
  h += '<div class="article-meta"><span><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:-2px;margin-right:2px;"><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg> ' + esc(a.author) + '</span><span><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="vertical-align:-2px;margin-right:2px;"><rect x="3" y="4" width="18" height="18" rx="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/></svg> ' + time + '</span>' + tags + '<span>' + likes + ' 喜欢</span></div></header>';
  h += '<div class="article-body" id="content"></div>';
  h += '<div class="article-actions"><button class="btn-like" id="like-btn" onclick="toggleLike()"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/></svg> 喜欢</button><span style="font-size:0.85rem;color:var(--color-text-muted);" id="like-text"></span></div>';
  h += '<section class="comment-section"><h3>评论 (<span id="cc">0</span>)</h3><div id="comments-area"></div>';
  h += '<textarea class="comment-input" id="comment-input" placeholder="写下想法..."></textarea>';
  h += '<input class="comment-input" id="comment-name" placeholder="昵称" style="min-height:auto;height:auto;margin-top:0.4rem;width:auto;min-width:160px;">';
  h += '<button class="btn-submit" onclick="postComment()">发表</button></section></article></div>';
  h += '<script>var aid=' + a.id + ',fp=localStorage.getItem("fp")||(function(){var f="fp"+Date.now()+Math.random();localStorage.setItem("fp",f);return f;})(),replyTo=null;';
  h += 'function init(){if(typeof marked==="undefined"){setTimeout(init,100);return;}document.getElementById("content").innerHTML=marked.parse(' + md + ');enhanceCodeBlocks();}init();loadComments();updateLikeState();';
  h += 'function enhanceCodeBlocks(){var pres=document.querySelectorAll(".article-body pre");for(var i=0;i<pres.length;i++){(function(pre){var code=pre.querySelector("code");var lang="";var cls=code?code.className||"":"";var m=cls.match(/language-(\w+)/);if(m)lang=m[1];var wrapper=document.createElement("div");wrapper.className="code-block-wrapper";var bar=document.createElement("div");bar.className="code-block-bar";bar.innerHTML=\'<span class="code-block-lang">\'+(lang||"code")+\'</span><button class="code-block-btn" title="展开" onclick="toggleExpand(this)"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 12 15 18 9"/></svg></button><span style="flex:1"></span><button class="code-block-btn" title="复制" onclick="copyCode(this)"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1"/></svg></button><button class="code-block-btn" title="全屏" onclick="toggleFullscreen(this)"><svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 3 21 3 21 9"/><polyline points="9 21 3 21 3 15"/><line x1="21" y1="3" x2="14" y2="10"/><line x1="3" y1="21" x2="10" y2="14"/></svg></button>\';pre.parentNode.insertBefore(wrapper,pre);wrapper.appendChild(bar);wrapper.appendChild(pre)})(pres[i])}}';
  h += 'function copyCode(btn){var code=btn.parentElement.parentElement.querySelector("pre code");var text=code?code.textContent:"";navigator.clipboard.writeText(text).then(function(){var orig=btn.innerHTML;btn.innerHTML=\'<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg>\';setTimeout(function(){btn.innerHTML=orig},1500)})}';
  h += 'function toggleExpand(btn){var wrapper=btn.parentElement.parentElement;var pre=wrapper.querySelector("pre");pre.classList.toggle("expanded");var poly=btn.querySelector("polyline");if(pre.classList.contains("expanded")){poly.setAttribute("points","18 15 12 9 6 15")}else{poly.setAttribute("points","6 9 12 15 18 9")}}';
  h += 'function toggleFullscreen(btn){var w=btn.parentElement.parentElement;w.classList.toggle("fullscreen");var pre=w.querySelector("pre");if(w.classList.contains("fullscreen")){document.body.style.overflow="hidden";if(!pre.querySelector(".line-numbers")){var lines=pre.textContent.split("\\n");var nums="";for(var li=1;li<=lines.length;li++)nums+=li+"\\n";var ln=document.createElement("div");ln.className="line-numbers";ln.textContent=nums;pre.insertBefore(ln,pre.firstChild);pre.style.display="flex";pre.style.gap="1rem"}var fsBtn=w.querySelector(".code-block-btn[title=\\"全屏\\"] polyline");if(fsBtn){fsBtn.setAttribute("points","4 14 10 14 10 20");var sec=document.createElementNS("http://www.w3.org/2000/svg","polyline");sec.setAttribute("points","20 10 14 10 14 4");fsBtn.parentNode.querySelector("svg").appendChild(sec);var l1=document.createElementNS("http://www.w3.org/2000/svg","line");l1.setAttribute("x1","14");l1.setAttribute("y1","10");l1.setAttribute("x2","21");l1.setAttribute("y2","3");fsBtn.parentNode.querySelector("svg").appendChild(l1);var l2=document.createElementNS("http://www.w3.org/2000/svg","line");l2.setAttribute("x1","3");l2.setAttribute("y1","21");l2.setAttribute("x2","10");l2.setAttribute("y2","14");fsBtn.parentNode.querySelector("svg").appendChild(l2)}}else{document.body.style.overflow=""}document.addEventListener("keydown",function esc(e){if(e.key==="Escape"){w.classList.remove("fullscreen");document.body.style.overflow="";document.removeEventListener("keydown",esc)}})}';
  h += 'function postComment(pid){var c=document.getElementById("comment-input").value.trim(),n=document.getElementById("comment-name").value.trim()||"匿名";if(!c)return;fetch("/api/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({article_id:aid,parent_id:pid||null,author_name:n,content:c})}).then(function(r){return r.json()}).then(function(){document.getElementById("comment-input").value="";replyTo=null;loadComments()})}';
  h += 'function loadComments(){fetch("/api/comments?article_id="+aid).then(function(r){return r.json()}).then(function(cs){document.getElementById("cc").textContent=countAll(cs);document.getElementById("comments-area").innerHTML=rc(cs)})}';
  h += 'function countAll(list){var n=0;for(var i=0;i<list.length;i++){n++;if(list[i].replies)n+=countAll(list[i].replies)}return n}';
  h += 'function rc(list,d){d=d||0;var h="";for(var i=0;i<list.length;i++){var c=list[i];h+=' + JSON.stringify('<div class="comment-box" style="margin-left:IDXpx"><div style="display:flex;justify-content:space-between;margin-bottom:0.2rem"><strong style="font-size:0.85rem">NAME</strong><span style="font-size:0.72rem;color:var(--color-text-muted)">TIME</span></div><p style="font-size:0.9rem;color:var(--color-text-secondary);margin:0.2rem 0">BODY</p><a class="reply-link" onclick="replyTo=CID;document.getElementById(\'comment-input\').focus()">回复</a></div>') + '.replace("IDX",d*16).replace("NAME",esc(c.author_name)).replace("TIME",(c.created_at||"").slice(0,16).replace("T"," ")).replace("BODY",esc(c.content)).replace("CID",c.id);if(c.replies&&c.replies.length)h+=rc(c.replies,d+1)}return h}';
  h += 'function toggleLike(){fetch("/api/likes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({article_id:aid,fingerprint:fp})}).then(function(r){return r.json()}).then(function(d){document.getElementById("like-count");updateLikeState()})}';
  h += 'function updateLikeState(){var b=document.getElementById("like-btn");fetch("/api/likes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({article_id:aid,fingerprint:fp})}).then(function(r){return r.json()}).then(function(d){b.innerHTML=d.liked?\'<svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/></svg> 已喜欢\':\'<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/></svg> 喜欢\';if(d.liked)b.classList.add("liked");else b.classList.remove("liked")})}';
  h += 'function esc(s){var d=document.createElement("div");d.textContent=s||"";return d.innerHTML}';
  h += '<\/script></body></html>';
  return h;
}

function esc(s) { return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
